### PR TITLE
Map Ctrl+0 to clear RPC console

### PR DESCRIPTION
**Pull request by RandyMcMillan**
Ctrl+0 (zero) is mapped to clear the gui console.

### CODE REVIEW

**Comment by RandyMcMillan** [comment]
Mapping Ctrl+0 to clear the console enables Ctrl + Ctrl - and Ctrl 0 functionality to be accessible from the same region on the keyboard. 


https://user-images.githubusercontent.com/152159/214204382-0343f726-a746-4f8e-ac24-5810433e68fd.mov

**Review by jarolrod — COMMENTED** [review]
Is this a common accessibility related shortcut to clear a console? Qt docs show that `Ctrl+0` is commonly used to reset the size of something back to its original size. For example in qt creator, its used to reset something to it's original size whether that be an image or font: https://doc.qt.io/qtcreator/creator-keyboard-shortcuts.html

The current shortcut to clear the console is `Control + L`. In relation to consoles, this is the normally used shortcut for the `clear` command.

**Comment by RandyMcMillan** [comment]
thanks for the feed back - maybe we just need to make these shortcuts more obvious in the gui - i will rethink this. But i still like having these related key commands close to one another - from a purely ergonomic perspective.

**Comment by jarolrod** [comment]
@RandyMcMillan for now, the shortcuts for actuating the console buttons are stated in the console welcome text. Maybe you'd like to explore making these more obvious?

**Comment by RandyMcMillan** [comment]
i "see" the issue - the dark green in dark mode doesn't have enough contrast to the back ground - i literally didn't see it. (my setup is unusual right now - working on a remote M1 - the screen share is small) :)

**Comment by jarolrod** [comment]
@RandyMcMillan I suppose this can be closed? wdyt?

**Pull request closed without merging**
