### PR TITLE
Added Tor icons to repo

### PR DESCRIPTION
**Pull request by Bosch-0**
Added the below icons to the repo which can be used for Tor network connectivity indicators #58. 

From previous discussion on issue.

> At some stage it would be nice to have some colored icons, but whilst the others are still in a black and white I think its important to stick with this style for now to keep consistency. I followed the same style that the connect icons use...

Link to the figma file where I did the icon designs > https://www.figma.com/file/FJ02rY3m8V9ZCDvoXjW39W/Bitcoin-Core?node-id=486%3A312

**In order:** Not connected -> connecting -> connected. 

image

Here is some examples of how they could be shown

image

image

image

### CODE REVIEW

**Comment by hebasto** [comment]
Concept ACK

**Comment by MarcoFalke** [comment]
What is the point of adding the icons if they are not shown in the gui?

**Comment by hebasto** [comment]
> What is the point of adding the icons if they are not shown in the gui?

I'll take care about it :)

**Comment by MarcoFalke** [comment]
Please add source/license to new files (contrib/debian/copyright) and optimize the png versions: https://github.com/bitcoin-core/bitcoin-maintainer-tools/blob/master/optimize-pngs.py

**Comment by jonatack** [comment]
Concept ACK

(make sure it renders to look more like an onion than, say, a bomb ;)

**Comment by Bosch-0** [comment]
> What is the point of adding the icons if they are not shown in the gui?

They will be soon as hebasto said. We have been discussing the implementation over at the bitcoin design slack. 

Though yes I guess I could have just passed the icons onto hebasto and he do a PR implementing them into the GUI but I figured some feedback on the design was important.

**Comment by Bosch-0** [comment]
> Concept ACK
> 
> 
> 
> (make sure it renders to look more like an onion than, say, a bomb ;)

There is both png and svg versions to play around with so the implementation can be a little flexible (using the svg's over pngs).

**Comment by jonasschnelli** [comment]
Concept ACK though I would prefer a simpler, less fine-grained icon.

**Comment by fanquake** [comment]
> What is the point of adding the icons if they are not shown in the gui?

I agree. These should be merged when they are being used; I don't think there's any need for us to start pulling in unused assets/imagery. If people are looking for feedback on designs, opening new issues in this repo or commenting in the existing threads is the way to go (I can see that was done in https://github.com/bitcoin-core/gui/issues/58).

**Pull request closed without merging**
