### PR TITLE
src/net.cpp: Fail to listen alert text break fix

### PR DESCRIPTION
**Pull request by RandyMcMillan**

### CODE REVIEW

**Comment by RandyMcMillan** [comment]
When another instance of bitcoin is running:

Screen Shot 2021-11-19 at 10 09 11 PM

Before:
Screen Shot 2021-11-19 at 10 09 18 PM

After:
Screen Shot 2021-11-19 at 10 10 37 PM

**Review by shaavan — APPROVED** [review]
ACK a5097f37ffead4790c11da66a8156b828f812ec5

Simple but necessary change. Before line break, the usage of `-listen=0` was not evident, and `-` could have confused a simple text hyphen. This PR removes the scope for that doubt.
Nice catch, @RandyMcMillan!

**Comment by katesalazar** [comment]
Concept ACK.

**Comment by hebasto** [comment]
Why don't use https://github.com/bitcoin-core/gui/blob/19815b096c6a2b2e0bcb802e9e5842e67952993e/src/qt/rpcconsole.cpp#L497 
which we already use in our code?

**Comment by hebasto** [comment]
@RandyMcMillan 

Could you move this PR into the main repo because it changes the code outside the `src/qt/` directory?

**Pull request closed without merging**
