### PR TITLE
Remove unnecessary wallet includes from rpcconsole.cpp

### PR DESCRIPTION
**Pull request by laanwj**
Fixes bitcoin/bitcoin#25266

### CODE REVIEW

**Comment by MarcoFalke** [comment]
cr ACK 09942736495502cedcef4b097dde6abd9327fbdb

Should be correct if it compiles?

**Comment by laanwj** [comment]
I think so! I also did a cursory check for direct use of wallet classes but couldn't find any. Everything goes through `WalletModel` etc.

**Review by hebasto — APPROVED** [review]
ACK 09942736495502cedcef4b097dde6abd9327fbdb.

It has become redundant since bitcoin-core/gui#118.

**Review by jarolrod — COMMENTED** [review]
post merge ACK https://github.com/bitcoin-core/gui/commit/09942736495502cedcef4b097dde6abd9327fbdb

**Pull request merged**
