### PR TITLE
fix for #191

### PR DESCRIPTION
**Pull request by RandyMcMillan**
@hebasto - here is a barebones fix for #191 
We can tweak the presentation in a follow up PR.

### CODE REVIEW

**Comment by hebasto** [comment]
@RandyMcMillan 

Thanks for fixing!

1. Did you find out the reason of head flickering?
2. Could using of `GUIUtil::TableViewLastColumnResizingFixer` be a better option as it is used in other places of the GUI?
3. Do you mind dropping `@` from the PR description?

**Review by jarolrod — COMMENTED** [review]
This PR does not fix #191 

It instead creates a new column in the Peer Table model. A fix to this should not hack on a new column so that the `User Agent` column does not glitch. Perhaps a refactor that creates a `PeerTableModelView` which makes use of `TableViewLastColumnResizingFixer` is more appropriate.

**PR:** Creates a new column to the right of `User Agent`
Screen Shot 2021-01-20 at 3 51 23 PM

**Comment by RandyMcMillan** [comment]
@jarolrod - It sounds like you have the motivation to implement a proper solution.
I will be excited to see how you refactor this into a proper MVC implementation.
I will be ecstatic to see it actually get merged!
Happy coding!

**Comment by jarolrod** [comment]
@RandyMcMillan was just relaying what I found while reviewing the PR. Wasn't trying to discourage you in anyway or come off as rude.

**Pull request closed without merging**
