### PR TITLE
test: Add missed header

### PR DESCRIPTION
**Pull request by hebasto**
Should fix MSVC link errors like [that](https://api.cirrus-ci.com/v1/task/4870882892447744/logs/build.log):
```
addressbooktests.obj : error LNK2019: unresolved external symbol "void __cdecl ConfirmMessage(class QString *,class std::chrono::duration<__int64,struct std::ratio<1,1000> >)" (?ConfirmMessage@@YAXPEAVQString@@V?$duration@_JU?$ratio@$00$0DOI@@std@@@chrono@std@@@Z) referenced in function "void __cdecl `anonymous namespace'::EditAddressAndSubmit(class EditAddressDialog *,class QString const &,class QString const &,class QString)" (?EditAddressAndSubmit@?A0x2e52698e@@YAXPEAVEditAddressDialog@@AEBVQString@@1V3@@Z) [C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\build_msvc\test_bitcoin-qt\test_bitcoin-qt.vcxproj]
wallettests.obj : error LNK2001: unresolved external symbol "void __cdecl ConfirmMessage(class QString *,class std::chrono::duration<__int64,struct std::ratio<1,1000> >)" (?ConfirmMessage@@YAXPEAVQString@@V?$duration@_JU?$ratio@$00$0DOI@@std@@@chrono@std@@@Z) [C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\build_msvc\test_bitcoin-qt\test_bitcoin-qt.vcxproj]
C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\build_msvc\x64\Release\test_bitcoin-qt.exe : fatal error LNK1120: 1 unresolved externals [C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\build_msvc\test_bitcoin-qt\test_bitcoin-qt.vcxproj]
```

### CODE REVIEW

**Comment by hebasto** [comment]
cc @fanquake @sipsorcery

**Review by fanquake — APPROVED** [review]
ACK 36e2d51b8f6bb0125911c831ba2b6fd022fca708

**Comment by hebasto** [comment]
The MSVC link issue was kind of intermittent. I guess, it was dependent on the actual order of processing of the source files.

**Comment by fanquake** [comment]
Yea. I guess the compiler is broken? Developers should not have to worry about putting files in the "right order" for it.

**Comment by hebasto** [comment]
Observing the same issue -- https://cirrus-ci.com/task/6646912535756800

:(

**Comment by fanquake** [comment]
No.

**Comment by fanquake** [comment]
> Looks like iwyu doesn't work with qt?

We might have to provide a mapping file, for it to work sanely? i.e https://github.com/include-what-you-use/include-what-you-use/blob/master/qt5_11.imp.

**Comment by hebasto** [comment]
> > Looks like iwyu doesn't work with qt?
> 
> We might have to provide a mapping file, for it to work sanely? i.e [include-what-you-use/include-what-you-use@`master`/qt5_11.imp](https://github.com/include-what-you-use/include-what-you-use/blob/master/qt5_11.imp?rgh-link-date=2023-05-17T13%3A29%3A36Z).

Added in https://github.com/bitcoin/bitcoin/pull/27710.

**Pull request merged**
