### PR TITLE
wallet: Remove unused AskPassphraseDialog::Decrypt

### LINKED ISSUE #1: gui: Remove unused `Decrypt` wallet
The Decrypt case is unused and should be removed. See

```
src/qt/askpassphrasedialog.h:        Decrypt     /**< Ask passphrase and decrypt wallet */
```

#### Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

### PR DESCRIPTION
**Pull request by hebasto**
Grabbed from #42 with an additional commit.

Fix #1.

### CODE REVIEW

**Comment by promag** [comment]
Concept ACK.

**Review by promag — COMMENTED** [review]
Code review ACK f886a20b02094d657ddb3d792d561d50f2107f07.

**Comment by MarcoFalke** [comment]
Please remove `bool encrypted` as well

**Comment by hebasto** [comment]
Updated f886a20b02094d657ddb3d792d561d50f2107f07 -> 4146a31ccbb012ff552f303113979b48c086532b ([pr109.01](https://github.com/hebasto/gui/commits/pr109.01) -> [pr109.02](https://github.com/hebasto/gui/commits/pr109.02), [diff](https://github.com/hebasto/gui/compare/pr109.01..pr109.02)):

- addressed @MarcoFalke's [comment](https://github.com/bitcoin-core/gui/pull/109#issuecomment-718056313):

> Please remove `bool encrypted` as well

**Comment by MarcoFalke** [comment]
ACK 4146a31ccbb012ff552f303113979b48c086532b

**Review by promag — COMMENTED** [review]
Code review ACK 4146a31ccbb012ff552f303113979b48c086532b.

**Pull request merged**
