### PR TITLE
Replace QMetaObject::invokeMethod with atomic operations

### PR DESCRIPTION
**Pull request by hebasto**
No need to read/write a data member in one thread if it is atomic.

### CODE REVIEW

**Review by promag — COMMENTED** [review]
An atomic bool would be enough?

Didn't want to mess with this in #120 because I think ballon filtering doesn't belong in transaction model. IMO the right place should be aware of what wallets are open.

**Comment by hebasto** [comment]
@promag 
> An atomic bool would be enough?

You're right. Reworked.

**Review by promag — COMMENTED** [review]
This doesn't work: `setProcessingQueuedTransactions` needs to be enqueued and proceed in between transaction notifications notifications.

**Comment by hebasto** [comment]
> This doesn't work: `setProcessingQueuedTransactions` needs to be enqueued and proceed in between transaction notifications.

Why?

**Comment by promag** [comment]
Transaction notifications are enqueued in `TransactionNotification::invoke` and by the time they are processed `setProcessingQueuedTransactions(false)` was already called.

**Comment by hebasto** [comment]
You mean that `setProcessingQueuedTransactions` must be placed into the same event queue as `updateTransaction`, i.e., coordinated?

**Comment by promag** [comment]
@hebasto yes, `processingQueuedTransactions()` value is worthless.

**Pull request closed without merging**
