### PR TITLE
Drop unused parameter in GUIUtil::get{Save|Open}FileName

### PR DESCRIPTION
**Pull request by hebasto**

### CODE REVIEW

**Review by jonatack — COMMENTED** [review]
Code review ACK c3c9d8db30a4148eeb14db0ac10f0f27fced1087 (but should this feature be used instead?)

**Comment by hebasto** [comment]
@jonasnick 
> but should this feature be used instead?

From https://doc.qt.io/qt-5/qfiledialog.html#getOpenFileName and https://doc.qt.io/qt-5/qfiledialog.html#getSaveFileName it follows that the `selectedFilter` out parameter is useful only in cases when multiple filters are passed to the `filter` parameter. That is not our case, right?

**Review by Talkless — APPROVED** [review]
utACK c3c9d8db30a4148eeb14db0ac10f0f27fced1087. Haven't even built, don't see anything to test.

**Review by luke-jr — CHANGES_REQUESTED** [review]
Concept NACK to removing the option entirely. This looks useful for allowing the user to save a plaintext backup file from the GUI, or a fully signed transaction in normal transaction format...

Maybe make it default to nullptr and omit in callers that don't use it, though..

**Comment by hebasto** [comment]
@luke-jr 
> This looks useful for allowing the user to save a plaintext backup file from the GUI...

Do you mean providing filters like `"Binary Wallet Data (*.dat);;Plain Text Wallet Data (*.txt)"` ?

**Comment by luke-jr** [comment]
Yes, see #230 :)

**Comment by hebasto** [comment]
@jonatack 
> but should this feature be used instead?

@luke-jr 
> Yes, see #230 :)

Closing.

**Pull request closed without merging**
