### PR TITLE
Catch invalid networks combination crash

### PR DESCRIPTION
**Pull request by furszy**
The app currently crashes if a network is set inside bitcoin.conf and
another one is provided as param.
The reason is an uncaught runtime_error.

### CODE REVIEW

**Review by jarolrod — APPROVED** [review]
tACK f4a11d7baf79ff6929d9ba8a934f53c4c7eb7c8e

Reproduced the crash on master by passing in a chain param while my bitcoin.conf specified a different chain:

**master**
```
libc++abi: terminating with uncaught exception of type std::runtime_error: Invalid combination of -regtest, -signet, -testnet and -chain. Can use at most one.
[1]    53813 abort      ./src/qt/bitcoin-qt -signet
```
Screen Shot 2022-12-28 at 10 30 47 AM

The PR branch fixes the issue for me:

**pr**
```
Error: Invalid combination of -regtest, -signet, -testnet and -chain. Can use at most one.
```

Screen Shot 2022-12-28 at 10 30 00 AM

Also tested the scenario where we show the intro to choose a datadir and a network parameter is passed; crash on master, fixed in pr branch.

**Review by johnny9 — APPROVED** [review]
tACK f4a11d7baf79ff6929d9ba8a934f53c4c7eb7c8e

Tested the changes with the following method. 

1. Set bitcoin.conf to testnet
``` ~/.bitcoin/bitcoin.conf
// /home/user/.bitcoin/.bitcoin.conf
testnet=1
```
2. ran bitcoin-qt with the following command `bitcoin-qt -signet`

On masterr (e9262ea32a6e1d364fb7974844fadc36f931f8c6):
```
~/github/gui$ ./src/qt/bitcoin-qt -signet                                                                                                                                                                                            
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
terminate called after throwing an instance of 'std::runtime_error'
  what():  Invalid combination of -regtest, -signet, -testnet and -chain. Can use at most one.
Aborted (core dumped)
```

With PR (f4a11d7baf79ff6929d9ba8a934f53c4c7eb7c8e):
```
~/github/gui$ ./src/qt/bitcoin-qt -signet
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Error: Invalid combination of -regtest, -signet, -testnet and -chain. Can use at most one.
```
And the following error dialog also appears now:
Screenshot from 2022-12-28 19-09-41

The change expands the try block to handle the exception thrown from GetChainName and is a reasonable approach to handling the error and giving the user expected gui error dialog. Some follow up to this bug might include functional test coverage with the settings testcases to prevent regression.  Another possible follow up is to handle the exception within ReadConfigFiles so bitcoind doesn't abort from the runtime_error.

**Review by hernanmarino — COMMENTED** [review]
Tested ACK. Also fails on master and succeds on PR.

**Review by john-moffett — APPROVED** [review]
ACK f4a11d7baf79ff6929d9ba8a934f53c4c7eb7c8e

**Review by pablomartin4btc — APPROVED** [review]
Tested ACK f4a11d7baf79ff6929d9ba8a934f53c4c7eb7c8e.
It behaves as expected, tested using different networks before and after the fix.
I agree with @johnny9 on functional tests if possible as a follow up ofc.

**Comment by furszy** [comment]
@hebasto

**Review by hebasto — APPROVED** [review]
ACK f4a11d7baf79ff6929d9ba8a934f53c4c7eb7c8e, tested on Ubuntu 22.04 (Qt 5.15.3).

**Pull request merged**
