### PR TITLE
Remove BDB version from the Information tab

### PR DESCRIPTION
**Pull request by hebasto**
Master (67d4643a1a763b893ee69f6bbbf59ef1f2cb0d51):
DeepinScreenshot_select-area_20201027161350

This PR:
DeepinScreenshot_select-area_20201027161449

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Yeah. Why not.
Code Review ACK c61024cae2c72bf1c5a7ed088298e44e66b513a4

**Comment by promag** [comment]
Is this even useful in the GUI? Sounds like one of those things that a GUI user doesn't care about. Not even in the RPC console. I'd just remove it..

**Comment by achow101** [comment]
Agree with @promag. It seems kind of useless to include this in the GUI.

**Comment by hebasto** [comment]
@promag 
> Is this even useful in the GUI? Sounds like one of those things that a GUI user doesn't care about. Not even in the RPC console. I'd just remove it..

@achow101 
> Agree with @promag. It seems kind of useless to include this in the GUI.

BDB version string removed completely :)
Please re-review.

**Comment by hebasto** [comment]
> We leave it in the console?

Not sure if I understand right what do you mean.

**Comment by promag** [comment]
Ah sorry @hebasto, forgot I was in another branch 🤦

**Comment by achow101** [comment]
ACK e4fc45a0115eea8ad7ad7505dfcfd8cbe50b96da

**Comment by jonasschnelli** [comment]
Probably fine to remove it. I guess nobody is using this information.
utACK e4fc45a0115eea8ad7ad7505dfcfd8cbe50b96da

**Comment by Sjors** [comment]
utACK e4fc45a

This information can still be found in the debug log whenever you load a wallet.

**Comment by promag** [comment]
ACK e4fc45a0115eea8ad7ad7505dfcfd8cbe50b96da.

**Review by jarolrod — APPROVED** [review]
Tested ACK e4fc45a
Built and tested on Arch Linux (Kernel 5.18.5) and macOS 10.15.7

**Pull request merged**
