### PR TITLE
Revert "Peertableview alternating row colors"

### PR DESCRIPTION
**Pull request by rebroad**
Reverts bitcoin-core/gui#298

I think this has made the table more cluttered now, and perhaps this pull request could be re-merged in the future once it's done with making the changes optional.

### CODE REVIEW

**Comment by jonatack** [comment]
I agree.

**Comment by hebasto** [comment]
> ... making the changes optional.

Done in #307.

**Comment by jarolrod** [comment]
My preference would be for #307. Some people were for this change, some against. #307 is the democratic option for appeasing both sides.

**Comment by Rspigler** [comment]
I am concept NACK this, without a plan for 307, which has now been closed

**Comment by rebroad** [comment]
I actually quite like the stripes now :) acquired taste I guess....!

**Pull request closed without merging**
