### PR TITLE
guiconstants: update ORG_DOMAIN to bitcoincore.org

### PR DESCRIPTION
**Pull request by MarnixCroes**
if desired, can also update `ORG_NAME` to _Bitcoin Core_

### CODE REVIEW

**Comment by laanwj** [comment]
> if desired, can also update ORG_NAME to Bitcoin Core

The reason that this was never done is because it changes where the Qt settings files are stored. For example this is `~/.config/<ORG_NAME>/<APP_NAME>`. 

i'm not sure what actually is the effect of changing the domain, but this shouldn't be done without checking.

**Comment by hebasto** [comment]
> if desired, can also update `ORG_NAME` to _Bitcoin Core_

Are there any issues with the current code? If not, then this PR lacks motivation.

**Comment by MarnixCroes** [comment]
ok, it came across in the qt-qml repo, I looked here and assumed it was forgotten to be updated.
nvm

**Comment by laanwj** [comment]
Right. i think qt-qml does something substantially different with regard to settings, so it may be warranted there.

**Pull request closed without merging**
