### PR TITLE
Fix checkbox layout in Create Wallet dialog

### PR DESCRIPTION
**Pull request by hebasto**
From https://github.com/bitcoin/bitcoin/issues/20555#issuecomment-747742627:
> 0.21.0rc3 compiled from source, Ubuntu 20.04 + i3: tested mainnet, testnet, and signet. created a descriptor wallet in qt, tested torv3 with addnode, and checked if anchors.dat is created on shutdown and removed on startup.
> 
> I've noticed the "Advanced options" label being cut-off in the wallet creation dialog.

This PR should fix this issue.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
cc @0xB10C

**Comment by 0xB10C** [comment]
This seems to fix it! Thanks.

rc3:
image


pr155:
image

**Comment by MarcoFalke** [comment]
review ACK e71b656f317f38ef0ba0874736f116dae39efc67

didn't test

**Comment by jonasschnelli** [comment]
Shouldn't this be a flexible (stretch layout instead of fixed pixles?

**Comment by MarcoFalke** [comment]
This can be reworked for 0.22, but I think for rc4 we should aim for a minimal fix

**Comment by hebasto** [comment]
> Shouldn't this be a flexible (stretch layout instead of fixed pixles?

The goal of this PR was the minimal fix as @MarcoFalke [said](https://github.com/bitcoin-core/gui/pull/155#issuecomment-747932196). Besides, the issue has spotted on i3 window manager, and the real problem could be much deeper.

**Comment by jonasschnelli** [comment]
post merge utACK the fix. I missed the rc4 issue or 0.21 tag...

**Pull request merged**
