### PR TITLE
qt: drop workaround for QTBUG-42503 which was fixed in Qt 5.5.0

### PR DESCRIPTION
**Pull request by prusnak**
Fixes https://github.com/bitcoin-core/gui/issues/101

### CODE REVIEW

**Comment by hebasto** [comment]
@prusnak 

Thanks! Do you mind providing a relevant screenshot from a retina display?

**Review by jarolrod — COMMENTED** [review]
Concept ACK

The workaround was actually introduced in 7247d103ffc2772b6dd997b7aa4d7147a8044d73 where we moved from a warning text to a warning icon. The `QPushButton` was used since at the time of that PR the [QTBUG-42503](https://bugreports.qt.io/browse/QTBUG-42503) was already known. Otherwise, going by the comment `"to work around missing HiDPI support of QLabel"` a `QLabel` would have been used.

Since `QLabel` is no longer affected by this bug, I guess fixing the workaround would mean refactoring the icon from a QPushButton to a QLabel. But, since we have additional logic with the modal overlay, maybe it makes more sense to keep it a `QPushButton`.

**Comment by prusnak** [comment]
> Thanks! Do you mind providing a relevant screenshot from a retina display?

Unfortunately, I have issues with linking the bitcoin-qt binary on my system with retina display due to unrelated error.

**Comment by jarolrod** [comment]
@prusnak @hebasto Here are screenshots taken on a Retina (HiDPI) display (2020 MacBook Pro).

While the line that is removed in this PR is no longer needed, I fail to see how it "fixes" the workaround. The workaround was to use a disabled `QPushButton` because `QLabel` had a regression where it failed to scale by the `devicePixelRatio` (this is no longer the case, see: [patch](https://codereview.qt-project.org/c/qt/qtbase/+/127002)). The fix would not be to continue to use the `QPushButton` unless it is decided to keep it.

**Master**
master

**PR**
pr

**Comment by jonasschnelli** [comment]
Tested ACK a2a3f4cd8d53e33b0e1b1aeff073b096ade034e9 -   
Bildschirmfoto 2021-01-26 um 10 40 43

**Pull request merged**
