### PR TITLE
scripted-diff: rename movie folder to animation

### PR DESCRIPTION
**Pull request by Bushstar**
Rename the movies directory and RES_MOVIES make variable to animation and RES_ANIMATION respectively. Movies is a bit of an unexpected term to be found.

### CODE REVIEW

**Comment by hebasto** [comment]
How about:
- `src/Makefile.qt.include`
- `src/qt/bitcoin.qrc`
- `src/qt/bitcoingui.cpp`
?

**Comment by Bushstar** [comment]
@hebasto bear with me! I thought some magic would pick up and apply the script. Will apply now.

**Comment by Bushstar** [comment]
@hebasto now updated to what I believe is correct.

**Comment by hebasto** [comment]
Just for the record: this was mentioned by @MarcoFalke in https://github.com/bitcoin/bitcoin/pull/19394#issuecomment-651169100:
> RES_ANIMATION would be a better name for the spinner, I guess

**Comment by Sjors** [comment]
Concept ACK, thanks for making this a scripted diff.

**Comment by Bushstar** [comment]
@Sjors thanks.

Still a WIP it seems. Guess the script also needs to rename the folder, will update.

**Comment by hebasto** [comment]
@Bushstar 
> Still a WIP it seems. Guess the script also needs to rename the folder, will update.

I think it is OK:
Screenshot from 2020-06-29 20-41-26

**Comment by Bushstar** [comment]
@hebasto CI failed on the last effort due to scripted-diff. I did not also rename the folder via script. First time using scripted-diff!

Now created the entire commit via command line and added those same commands to the scripted-diff. Hopefully this time it will succeed. I'll keep an eye on it and update it as needed. Thanks everyone for your patience.

https://travis-ci.org/github/bitcoin-core/gui/jobs/703204253#L422

**Comment by Bushstar** [comment]
@fanquake looks like all tests should pass but one build ran out of time, please give it a nudge.

**Comment by hebasto** [comment]
@Bushstar 
> @fanquake looks like all tests should pass but one build ran out of time, please give it a nudge.

It is a known problem. See #12.

**Comment by hebasto** [comment]
Concept ACK.

**Comment by MarcoFalke** [comment]
ACK 80968cff68f4d11d98a2a6670846eafbb2803f4f

**Pull request merged**
