### PR TITLE
Warn when sending to already-used Bitcoin addresses

### PR DESCRIPTION
**Pull request by luke-jr**
Entering a used address in the GUI Send tab makes the field turn yellow. Sending to a used address from the GUI prompts with detailed information about prior usage, as well as a note about best practices to avoid address reuse.

Continued from https://github.com/bitcoin/bitcoin/pull/15987 (significantly modified/rewritten - no more bloom filter)

Depends on https://github.com/bitcoin/bitcoin/pull/22693 for non-GUI changes

### CODE REVIEW

**Comment by RandyMcMillan** [comment]
Concept ACK

**Comment by Rspigler** [comment]
Concept ACK.  Can test when taken out of Draft

**Comment by katesalazar** [comment]
Great idea, thanks. Hope doesn't break anything.

**Comment by hebasto** [comment]
Closing this due to lack of activity. Feel free to reopen.

**Pull request closed without merging**
