### PR TITLE
Remove proxy checkboxes from options

### PR DESCRIPTION
**Pull request by prayank23**
Never used these checkboxes. No response on IRC or SE so I am assuming its not useful: https://bitcoin.stackexchange.com/questions/109636/understanding-network-options-in-bitcoin-core-gui

Will get some extra space and need to add checkboxes for `onlynet` next: https://github.com/bitcoin-core/gui/issues/413

### CODE REVIEW

**Review by jarolrod — COMMENTED** [review]
NACK

The use cases for these check boxes is specifying where to use a proxy and then setting a different proxy for usage with tor. 

You can't go and start removing code because "you don't use it"; especially when you don't provide any justification and don't fully understand what it's doing.

**Comment by prayank23** [comment]
> The use cases for these check boxes is specifying where to use a proxy and then setting a different proxy for usage with tor.

Can you share docs or steps how is this options being used or helpful?

**Comment by hebasto** [comment]
https://bitcoin.stackexchange.com/a/109651/113152

**Comment by prayank23** [comment]
@hebasto Thanks for answering. Will close this PR as I think removal isn't required although I think some changes or discussion is required because:

1. I2P is added which uses 127.0.0.1:7656 as proxy
2. Few PRs are open in bitcoin/bitcoin which change behaviour of proxy and onlynet. It was discussed that proxy is just a proxy and should remain same for all networks if it can be used.

**Pull request closed without merging**
