### PR TITLE
Network Watch tool

### PR DESCRIPTION
**Pull request by luke-jr**
Now that the crash bug (https://github.com/bitcoinknots/bitcoin/issues/4) has been tracked down, this seems ready for re-opening for Core.

(Originally https://github.com/bitcoin/bitcoin/pull/9849)

### CODE REVIEW

**Comment by jarolrod** [comment]
Concept ACK

In general, I'm in favor of not having tons of pop-out windows. May be worth exploring this as a new tab. 

If possible, can you include screenshots of this in action in the OP?

**Comment by luke-jr** [comment]
Not sure how to add inline images on GitHub, but there's a sceenshot on the wiki: https://en.bitcoin.it/wiki/File:Bitcoinknots-netwatch.png

**Comment by luke-jr** [comment]
As for "pop out windows", I think that's the correct UX for features like this. Having a tab in the main window just doesn't seem to fit well.

Maybe a new debug-window-alike for statistics?

**Review by jarolrod — COMMENTED** [review]
Have not yet reviewed the code, but: 

Commit 47711fdbc4b5d7f53aa778bcb1af34fc699ab81f must be broken off and opened in the core repo if it is needed. Then this can be based on the PR that would be open. The change to to `validationinterface` cannot be done in this repo.

Additionally, the commit history is not clean. The last 4 commits could be squashed onto ae6804e1a1e52611c7f98c6194a8384dda7abe60

**Comment by rebroad** [comment]
@luke-jr  how about a screenshot?

**Comment by rebroad** [comment]
concept NACK - at least, so far, I'm struggling to understand the use case for this. I'd have thought something more command line would make sense, as surely there'd be so much data that it would scroll by too quickly to be useful.

**Comment by jonatack** [comment]
Concept ACK if I'm understanding from the earlier PR. Suggest describing what it does and the use case (what and why) in the pull description.

**Comment by hebasto** [comment]
Closing this due to lack of activity. Feel free to reopen.

**Pull request closed without merging**
