### PR TITLE
refactor: Use enum type as switch argument in *TableModel

### PR DESCRIPTION
**Pull request by hebasto**
This PR makes code more maintainable by leveraging `-Wswitch` compiler warnings.

Only the `RecentRequestsTableModel` is not refactored, because its `enum ColumnIndex` contains additional `NUMBER_OF_COLUMNS` value.

No behavior change.

### CODE REVIEW

**Comment by hebasto** [comment]
Rebased aeb11d3704faa7c2cc71f4e23462e5dcd050c6df -> dae033e3fd5c910e961f5f5553004710fb27dd43 ([pr166.01](https://github.com/hebasto/gui/commits/pr166.01) -> [pr166.02](https://github.com/hebasto/gui/commits/pr166.02)) due to the conflict with #162.

**Comment by hebasto** [comment]
Rebased dae033e3fd5c910e961f5f5553004710fb27dd43 -> d4508f1e82b2bbf591af2cad25933d5050c404bb ([pr166.02](https://github.com/hebasto/gui/commits/pr166.02) -> [pr166.03](https://github.com/hebasto/gui/commits/pr166.03)) due to the conflict with #161.

**Review by promag — COMMENTED** [review]
Concept ACK.

It's not clear to me if `data()` implementation should check for out of bounds. I think Qt views and proxy model behave correctly by querying data inside `columnCount()` and `rowCount()`.

As follow up:
 - move `AddressTableModel::columns` member to `priv` instance
 - drop `section < columns.size()` check in `AddressTableModel::headerData`

**Comment by hebasto** [comment]
@promag
> It's not clear to me if `data()` implementation should check for out of bounds. I think Qt views and proxy model behave correctly by querying data inside `columnCount()` and `rowCount()`.

At least, these changes do not affect the current behavior, right?

**Comment by hebasto** [comment]
@jonasschnelli Maybe tag this pr with `22.0` milestone?

**Comment by hebasto** [comment]
Rebased d4508f1e82b2bbf591af2cad25933d5050c404bb -> 1d5d832d5c045cbbe3a0f4aa8fc29e52ecadc182 ([pr166.03](https://github.com/hebasto/gui/commits/pr166.03) -> [pr166.04](https://github.com/hebasto/gui/commits/pr166.04)) due to the conflict with #179.

**Review by jarolrod — COMMENTED** [review]
ACK 1d5d832d5c045cbbe3a0f4aa8fc29e52ecadc182, tested on macOS 11.1 Qt 5.15.2

This refactor brings a safer `switch` statement design to the address, ban, peer, and transaction table models. It also brings us in accordance with the `switch` design recommendation included in [developer-notes.md](https://github.com/bitcoin/bitcoin/blob/master/doc/developer-notes.md#c-data-structures). 

The ability to leverage the `-Wswitch` compiler warning, as mentioned in the OP, is another benefit of this refactor. An example of the benefit this brings can be shown by considering a scenario where a new Address type is introduced, and the author forgets to update the code to consider the new type. In such a scenario, the compiler will warn about this, thus preventing errors.

**Review by leonardojobim — COMMENTED** [review]
ACK https://github.com/bitcoin-core/gui/pull/166/commits/ab8a747d1ced9f20ca32f9898418be70670da71a, tested on Ubuntu 20.04 Qt 5.12.8

**Review by promag — COMMENTED** [review]
Code review ACK 1d5d832d5c045cbbe3a0f4aa8fc29e52ecadc182.

**Comment by hebasto** [comment]
@leonardojobim 
> ACK [ab8a747](https://github.com/bitcoin-core/gui/commit/ab8a747d1ced9f20ca32f9898418be70670da71a), tested on Ubuntu 20.04 Qt 5.12.8

Thank you for your review!

Do you mind mentioning the _top_ pr commit with your ACK, i.e., 1d5d832d5c045cbbe3a0f4aa8fc29e52ecadc182, not ab8a747d1ced9f20ca32f9898418be70670da71a?

**Comment by leonardojobim** [comment]
No problem. Changed it to the top PR commit.

**Pull request merged**
