### PR TITLE
Add "Copy address" item to the context menu in the Peers table

### PR DESCRIPTION
**Pull request by hebasto**
It seems a useful feature. Related to #262.

### CODE REVIEW

**Comment by wodry** [comment]
Thanks, I applied only the last commit 03a2b7426446693505af66280fd6868c210bd035 to the master branch, built it on Debian 10 Buster, and copying of the node address incl. port works. One can afterwards paste it from the clipboard.
I do not understand the code, just applied and tested it.
Screenshot:

bildschirmfoto

**Review by jarolrod — COMMENTED** [review]
Concept ACK

since we are adding the ability to copy the address, is there any reason to still allow this to show up/be clicked on:

Screen Shot 2021-04-05 at 1 21 42 PM

**Comment by hebasto** [comment]
> since we are adding the ability to copy the address, is there any reason to still allow this to show up/be clicked on:

Why not?

**Comment by hebasto** [comment]
Rebased 03a2b7426446693505af66280fd6868c210bd035 -> bb36f6e60b961d50b753c35e36c1833f862f8b0c ([pr264.01](https://github.com/hebasto/gui/commits/pr264.01) -> [pr264.02](https://github.com/hebasto/gui/commits/pr264.02)) due to the conflict with #260.

**Review by jarolrod — COMMENTED** [review]
tACK bb36f6e60b961d50b753c35e36c1833f862f8b0c

Tested on macOS 11.2.3 Qt 5.15.2. The menu action works as it should.
Screen Shot 2021-04-15 at 10 53 14 PM

#263, which this is based on, is on my plate to review for tomorrow. 🥃

**Comment by promag** [comment]
If you copy a row with the keyboard shortcut and paste it you will get rubbish.

**Comment by hebasto** [comment]
@promag 
> If you copy a row with the keyboard shortcut and paste it you will get rubbish.

I suppose you are testing on macOS, no?

**Comment by hebasto** [comment]
@promag
> If you copy a row with the keyboard shortcut and paste it you will get rubbish.

It appears, the problem is much bigger, at least on Linux -- see #283.

Although keyboard shortcuts are out of this PR scope, do you think it'd better to postpone this PR until #283 is fixed?

**Comment by promag** [comment]
Needs rebase.

**Comment by MarcoFalke** [comment]
> Needs rebase.

why?

**Comment by promag** [comment]
> > Needs rebase.
> 
> why?

Right, it doesn't actually need, just github showing more commits.

**Comment by MarcoFalke** [comment]
Ok, I removed commits from showing up

**Comment by hebasto** [comment]
Rebased due to the conflict with #18.

@promag 
> If you copy a row with the keyboard shortcut and paste it you will get rubbish.

This is fixed in #18.

**Comment by hebasto** [comment]
This branch is currently broken, leaving it for now up for grabs.

**Comment by jarolrod** [comment]
@hebasto no longer up for grabs, picked up in #318

**Pull request closed without merging**
